# Generated by Django 5.1.3 on 2024-12-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_name', models.CharField(max_length=255)),
                ('poke_type', models.CharField(max_length=255)),
            ],
        ),
    ]
